pub mod advanced_prefabs;
pub mod animation;
#[cfg(feature = "editor")]
pub mod animation_editor;
pub mod animation_graph;
pub mod archetype_library;
pub mod asset_database;
pub mod asset_importers;
pub mod asset_operations;
pub mod asset_pipeline_2d;
#[cfg(feature = "editor")]
pub mod asset_preview;
pub mod asset_reference_resolver;
pub mod asset_tools;
pub mod audio_mixer;
#[cfg(feature = "editor")]
pub mod automation_bridge;
pub mod autosave_manager;
pub mod build_placement;
pub mod build_profiles;
pub mod build_report;
pub mod build_settings;
pub mod camera;
#[cfg(feature = "editor")]
pub mod command_palette;
pub mod component;
pub mod component_registry;
pub mod component_tools;
pub mod component_validation;
#[cfg(feature = "editor")]
pub mod content_drag;
pub mod crash_reporter;
#[cfg(feature = "editor")]
pub mod create_asset_modal;
pub mod developer_console;
pub mod development_workflow;
pub mod diagnostics;
#[cfg(feature = "editor")]
pub mod docking_panel;
#[cfg(feature = "editor")]
pub mod document_manager;
pub mod document_schema;
#[cfg(feature = "editor")]
pub mod editor_asset_connector;
#[cfg(feature = "editor")]
pub mod editor_command;
#[cfg(feature = "editor")]
pub mod editor_core;
#[cfg(feature = "editor")]
pub mod editor_history;
#[cfg(feature = "editor")]
pub mod editor_python;
#[cfg(feature = "editor")]
pub mod editor_shell;
#[cfg(feature = "editor")]
pub mod editor_spatial_tools_2d;
#[cfg(feature = "editor")]
pub mod editor_tabs;
#[cfg(feature = "editor")]
pub mod editor_tools;
#[cfg(feature = "editor")]
pub mod editor_ui;
#[cfg(feature = "editor")]
pub mod editor_view_settings;
#[cfg(feature = "editor")]
pub mod editor_workflow_2d;
#[cfg(feature = "editor")]
pub mod editor_workspace;
pub mod engine_backend;
pub mod engine_programming;
pub mod entity_id;
pub mod error_handler;
pub mod event_bus;
#[cfg(feature = "editor")]
pub mod file_browser;
pub mod forge_ai;
pub mod formation;
pub mod game_api;
pub mod game_clock;
pub mod hierarchy_manager;
pub mod input_map;
#[cfg(feature = "editor")]
pub mod inspector_editor;
pub mod layer_visibility;
#[cfg(feature = "editor")]
pub mod layout_manager;
pub mod logger;
pub mod luau_scripting;
pub mod manifest_builder;
pub mod material_system;
pub mod miniforge_2d;
pub mod native_library;
pub mod node_path;
pub mod packaging_manager;
pub mod packed_scene;
#[cfg(feature = "editor")]
pub mod play_mode_manager;
pub mod plugin_manager;
pub mod prefab_manager;
pub mod prefab_overrides;
pub mod prefab_serializer;
pub mod prefab_workflow;
pub mod profiler;
#[cfg(feature = "editor")]
pub mod project_browser;
pub mod project_config;
#[cfg(feature = "editor")]
pub mod project_launcher;
pub mod project_manager;
pub mod project_package;
pub mod project_settings;
pub mod project_storage;
pub mod project_system;
pub mod project_templates;
pub mod project_validator;
pub mod render_2d;
pub mod render_3d;
pub mod resource_manager;
#[deprecated(note = "Rhai was removed; import luau_scripting instead")]
pub mod rhai_scripting;
pub mod rts_command_queue;
pub mod runtime_config;
pub mod runtime_exporter;
pub mod runtime_manifest_loader;
pub mod safe_mode;
pub mod scene;
pub mod scene_hierarchy;
pub mod scene_manager;
pub mod scene_save_manager;
pub mod scene_serializer;
pub mod scene_signal;
pub mod scene_tools;
pub mod scene_tree;
pub mod scene_validator;
pub mod scene_view_tools;
pub mod script;
#[cfg(feature = "editor")]
pub mod script_debugger;
#[cfg(feature = "editor")]
pub mod script_editor;
pub mod script_host_2d;
pub mod script_manager;
pub mod selection_manager;
pub mod service_registry;
#[cfg(feature = "editor")]
pub mod session_recovery;
pub mod spatial_index;
#[cfg(feature = "editor")]
pub mod sprite_editor;
pub mod system;
pub mod system_audit;
pub mod system_scheduler;
#[cfg(feature = "editor")]
pub mod tab_manager;
pub mod tags_layers_manager;
#[cfg(feature = "editor")]
pub mod theme;
#[cfg(feature = "editor")]
pub mod tile_brush;
pub mod tilemap_layers;
pub mod ui;
pub mod ui_advanced;
pub mod ui_canvas;
pub mod ui_runtime;
pub mod update_093;
pub mod update_0934;
pub mod upgrade_manifest;
pub mod vector_canvas_2d;
pub mod version;
pub mod view_mode;
pub mod visual_graph_serializer;
#[cfg(feature = "editor")]
pub mod visual_input_editor;
pub mod visual_scripting;
pub mod world;
#[cfg(feature = "editor")]
pub mod xcode_integration;
